sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install -g firebase-tools'
  - 'npm install -g karma'
  - 'npm install -g grunt-karma'
  - 'bower install'
  - 'npm install'
  - 'grunt wiredep'
  - 'grunt build'
after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}
